### ISSUE TITLE
Dokan support?

### ISSUE THREAD

**Issue by aaronbesson** [Irdroid/woo-instant-notifications#1]
Any plans to support Dokan? Would be awesome to allow vendors to receive notifications also.

**Comment by Irdroid** [comment]
It should be supported as it is based on woocommerce

**Comment by aaronbesson** [comment]
Unfortunately, doesn't look so, vendors are not receiving a new order notification, only admin

**Comment by Irdroid** [comment]
To be able to notify vendors , the template for the particular instant notification shall be edited and all vendor emails shall be added in the Recepients field. `<a href="https://ibb.co/MgyxVpP"><img src="https://i.ibb.co/j89PMG3/Dokan-support.png" alt="Dokan-support" border="0"></a><br /><a target='_blank' href='https://babynamesetc.com/boy/unusual'>h and m baby boy</a><br />`

**Comment by aaronbesson** [comment]
Hey, I tried that, and all the vendors get an email when a new purchase is made from any, and that's not how it should work.

Vendor A, should receive emails when users buy from Vendor A.

When I add: vendor A email, vendor B email, vendor c email, and a customer places an order from Vendor A, vendor B and vendor C are receiving an email notification about Vendor A's order, that shouldn't happen.

**Comment by Irdroid** [comment]
Dokan support should be achieved easily with a minor code change. Are you willing to contribute?

**Comment by Irdroid** [comment]
To be assigned to developer
