### ISSUE TITLE
Don´t Save the Options

### ISSUE THREAD

**Issue by bschultzki** [Irdroid/woo-instant-notifications#10]
Hello,

In your plugin settings, it doesn't save changes.

Best regards.

I used the 7.3 php version.

**Comment by Irdroid** [comment]
You can try enabling WordPress debug mode, then , try to save the settings and provide the log file here, so that we can check what is the issue

**Comment by bschultzki** [comment]
My sincere apologies, the error was mine, I had to read the documentation well.

Thank you
