### ISSUE TITLE
Connection with the printer

### ISSUE THREAD

**Issue by kassinf** [Irdroid/woo-instant-notifications#2]
Hi,

Your plug-in is amazing. I couldn't find a how to about it... 

"How it works? The plugin sends formatted plain text emails based on order status change. On the receiving side a Mozilla thunderbird email autoprint addon is used with filters in order to print the receipts on the thermal printer."

How to do this connection with thunderbird and where can I find a documentation about it. 

Thx in advance.

**Comment by Irdroid** [comment]
Thank you!

I should make a video how-to . You need to install a auto print plug-in for Mozilla Thunderbird and setup filter that will detect a keyword in the email subject that will trigger the print automatically.

Regards,
Georgi

On September 7, 2019 7:01:19 PM GMT+03:00, kassinf <notifications@github.com> wrote:
>Hi,
>
>Your plug-in is amazing. I couldn't find a how to about it... 
>
>"How it works? The plugin sends formatted plain text emails based on
>order status change. On the receiving side a Mozilla thunderbird email
>autoprint addon is used with filters in order to print the receipts on
>the thermal printer."
>
>How to do this connection with thunderbird and where can I find a
>documentation about it. 
>
>Thx in advance. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Irdroid/woo-instant-notifications/issues/2

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kassinf** [comment]
It's great Georgi. I would love it if you do this how to video.

Thank you ans congrats.

**Comment by Irdroid** [comment]
Explained
