### ISSUE TITLE
Address Line #2 does not come through

### ISSUE THREAD

**Issue by itjbind** [Irdroid/woo-instant-notifications#7]
Hi there,
Many of our customers put information in address line 2. I tried using various short codes (listed below) but none seem to work. Please let me know if I am doing something wrong. If not, can you please update the plugin (through wordpress.org, the last update was 5 months ago ) to add support for this. It would be super helpful!

{order_shipping_address_2}
{shipping_address_2}
{order_billing_address_2}
{billing_address_2}

**Comment by Irdroid** [comment]
unfortunately these shortcodes are not in the plugin, so address line 2 is not available at the moment

**Comment by itjbind** [comment]
Will you add support for this soon? Any time frame?

**Comment by Irdroid** [comment]
Support for this is not planned for now

**Comment by Irdroid** [comment]
These features are now available in the PRO version -> [Here](https://ji4ka.com/woo-instant-notifications-pro/)
