### ISSUE TITLE
Disable customer email

### ISSUE THREAD

**Issue by itjbind** [Irdroid/woo-instant-notifications#8]
Hi there,

I only want my shop manager to get the email from the notification. However, by default your plugin pulls the customer's email too from the order and sends them the notification as well. I want to disable this so my customers do not get the receipt email. How do I do this?

**Comment by Irdroid** [comment]
Actually woocommerce send the order details to the customer. The plugin has a tick 'send to customer' which either send the template to the customer or not

**Comment by itjbind** [comment]
No I am not talking about the order details. What I'm trying to say is that they are getting the notification email I designed with your plugin. I don't want them to receive this. I only want admins to see this.
Order #: {order_number}
**************************
To: {order_billing_name}
tel: {order_billing_phone}
**************************
Address
**************************
{order_shipping_address_1}
{order_shipping_city}, {order_shipping_state}, {order_shipping_postcode}

**Comment by Irdroid** [comment]
Check this -> https://hwgroup-bg.com/product/woo-instant-notifications-pro-license/

If you get this you will be able to test early plugin version updates and more features
