### ISSUE TITLE
can't get the orders to print

### ISSUE THREAD

**Issue by Cesarmcp** [Irdroid/woo-instant-notifications#9]
I receive new order notifications emails and I can see the notifications on the VIew notifications tab.
I can print a test print on the thermal printers, it's plugged in, driver installed and cables firmely secure. So why won't the orders print? i am using PayPal Sandbox to place test orders.

**Comment by Irdroid** [comment]
Have you setup the printingtools autoprint plugin for Mozilla Thunderbird?

Have you added a message filter with a keyword for the orders?

Regards
Georgi

On April 12, 2020 11:41:02 AM GMT+03:00, Cesarmcp <notifications@github.com> wrote:
>I receive new order notifications emails and I can see the
>notifications on the VIew notifications tab.
>I can print a test print on the thermal printers, it's plugged in,
>driver installed and cables firmely secure. So why won't the orders
>print? i am using PayPal Sandbox to place test orders.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Irdroid/woo-instant-notifications/issues/9

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Irdroid** [comment]
We can schedule a TeamViewer session on Monday to help you set it up

Just propose a suitable time for you

**Comment by Cesarmcp** [comment]
I will download this plugin and install it. Do I have to use Thunderbild as the email client? 
or can I use my regular emails clients such as Yahoo or Gmail?

**Comment by Cesarmcp** [comment]
https://github.com/Irdroid/woo-instant-notifications/issues/9#issuecomment-612586709

I am in California what time is it there now? Now would be a great time to do this. :)

**Comment by Irdroid** [comment]
It is 10:30 PM here Europe/Bulgaria

On April 12, 2020 10:26:21 PM GMT+03:00, Cesarmcp <notifications@github.com> wrote:
>https://github.com/Irdroid/woo-instant-notifications/issues/9#issuecomment-612586709
>
>I am in California what time is it there now? Now would be a great time
>to do this. :)
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Irdroid/woo-instant-notifications/issues/9#issuecomment-612664270

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Irdroid** [comment]
You have to use Mozilla Thunderbird and these plugins if you need automatic receipt printing. 

On April 12, 2020 10:18:55 PM GMT+03:00, Cesarmcp <notifications@github.com> wrote:
>I will download this plugin and install it. Do I have to use
>Thunderbild as the email client? 
>or can I use my regular emails clients such as Yahoo or Gmail?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Irdroid/woo-instant-notifications/issues/9#issuecomment-612663269

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Cesarmcp** [comment]
would now work for you?

**Comment by Irdroid** [comment]
Sorry,

It is late and I am not at the office.
Let's schedule it

On April 12, 2020 10:41:01 PM GMT+03:00, Cesarmcp <notifications@github.com> wrote:
>would now work for you?
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Irdroid/woo-instant-notifications/issues/9#issuecomment-612665984

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Cesarmcp** [comment]
No problem. I downloaded Thunderbird and set it up as my default email client. Now I will try to do this one printingtools autoprint plugin for Mozilla Thunderbird?

**Comment by Cesarmcp** [comment]
Found the Mozilla Add-On link and, I downloaded it to my Pc.  (printingtools-1.3.0-tb.xpi)
when I  tried to installed it from the file I received this message. "The add on downloaded from this site could not be added because it appeared to be corrupted." I am stuck. :(
